version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: black
    versions:
    - 21.4b0
    - 21.4b1
  - dependency-name: pre-commit
    versions:
    - 2.10.0
    - 2.10.1
    - 2.11.0
    - 2.11.1
    - 2.12.0
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
    - 3.1.7
    - 3.1.8
  - dependency-name: djangorestframework
    versions:
    - 3.12.2
    - 3.12.3
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: flake8-bugbear
    versions:
    - 20.11.1
    - 21.3.1
    - 21.3.2
  - dependency-name: django-cors-headers
    versions:
    - 3.7.0
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: pytest-cov
    versions:
    - 2.11.1
  - dependency-name: isort
    versions:
    - 5.7.0
  - dependency-name: codecov
    versions:
    - 2.1.11
  - dependency-name: pytest-django
    versions:
    - 4.1.0
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: http-proxy-middleware
    versions:
    - 1.0.6
    - 1.1.0
    - 1.1.1
    - 1.1.2
    - 1.2.0
    - 1.3.0
  - dependency-name: flow-bin
    versions:
    - 0.143.1
    - 0.144.0
    - 0.145.0
    - 0.146.0
    - 0.147.0
    - 0.148.0
  - dependency-name: react-bootstrap
    versions:
    - 1.4.3
    - 1.5.0
    - 1.5.1
    - 1.5.2
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: bootstrap
    versions:
    - 4.6.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: react-bootstrap-typeahead
    versions:
    - 5.1.4
  - dependency-name: react
    versions:
    - 16.14.0
