language: python
python:
  - 3.7
env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1
install:
  - pip install -q pipenv
  - pipenv install --dev
script:
  - flake8 backend
  - pytest backend --cov-config=.coveragerc
after_success:
  - codecov
