# Generated by Django 2.2.7 on 2019-11-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('book', '0002_publisher_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
