# Generated by Django 3.2.6 on 2021-08-03 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20210802_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='gtin',
            new_name='ean',
        ),
    ]
