# Generated by Django 2.2.6 on 2019-10-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
