# Generated by Django 2.2.7 on 2019-11-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['first_name']},
        ),
        migrations.AddField(
            model_name='person',
            name='type',
            field=models.ManyToManyField(to='person.PersonType'),
        ),
    ]
