# Generated by Django 2.2.7 on 2019-11-06 03:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('person', '0002_auto_20191106_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='person',
            name='nickname',
        ),
    ]
