# Generated by Django 2.2.7 on 2019-11-11 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('person', '0003_auto_20191106_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='type',
        ),
    ]
