# Generated by Django 2.2.7 on 2019-11-06 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('person', '0002_auto_20191106_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAgeClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookPublisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookTextualClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('original_title', models.CharField(max_length=100)),
                ('age_classification', models.ManyToManyField(to='book.BookAgeClassification')),
                ('person', models.ManyToManyField(to='person.Person')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.BookPublisher')),
                ('textual_classification', models.ManyToManyField(to='book.BookTextualClassification')),
            ],
        ),
    ]
